### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by winneryong** [ChiChou/etacsufbo#11]
ClaireLeeMacBook-Pro:etacsufbo clairelee$ ./cli.js index-7d4be8fb5d-1.js
/Users/clairelee/Developer/etacsufbo/node_modules/esprima/dist/esprima.js:3492
	        this.length = code.length;
	                          ^

TypeError: Cannot read property 'length' of undefined
    at new Scanner (/Users/clairelee/Developer/etacsufbo/node_modules/esprima/dist/esprima.js:3492:28)
    at new Parser (/Users/clairelee/Developer/etacsufbo/node_modules/esprima/dist/esprima.js:418:25)
    at Object.parse (/Users/clairelee/Developer/etacsufbo/node_modules/esprima/dist/esprima.js:115:19)
    at Object.exports.expression.code [as expression] (/Users/clairelee/Developer/etacsufbo/lib/util.js:100:11)
    at wrap (/Users/clairelee/Developer/etacsufbo/lib/simplifier.js:23:28)
    at Controller.leave (/Users/clairelee/Developer/etacsufbo/lib/simplifier.js:115:22)
    at Controller.__execute (/Users/clairelee/Developer/etacsufbo/node_modules/estraverse/estraverse.js:397:31)
    at Controller.replace (/Users/clairelee/Developer/etacsufbo/node_modules/estraverse/estraverse.js:618:31)
    at Object.replace (/Users/clairelee/Developer/etacsufbo/node_modules/estraverse/estraverse.js:718:27)
    at Object.simplify (/Users/clairelee/Developer/etacsufbo/lib/simplifier.js:40:20)

**Comment by ChiChou** [comment]
Unable to reproduce

**Comment by winneryong** [comment]
[index-7d4be8fb5d-1.js.zip](https://github.com/ChiChou/etacsufbo/files/1734750/index-7d4be8fb5d-1.js.zip)
请试试这个js

**Comment by ChiChou** [comment]
这个脚本没有混淆，只是压缩了变量名和删除空白字符而已
